extraction:
  cpp:
    prepare:
      packages:
        - libboost-all-dev
        - libopenmpi-dev
        - libxml2-dev
        - libeigen3-dev
    configure:
      command:
        - cmake -DPRECICE_PETScMapping=OFF -DPRECICE_PythonActions=OFF .
